### 1. LOGIN
POST http://localhost:5188/api/pbl3/auth/customer_login
Content-Type: application/json

{
  "userName": "duythuan",
  "hashPassword": "19082173"
}

### 2. CHAT MESSAGE 
POST http://localhost:5188/api/pbl3/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA4ZGVhOTlhLWZhNGItNDE1Mi04NDQ4LTAxODk2ZjZiYjFlNyIsIlVzZXJJRCI6IjA4ZGVhOTlhLWZhNGItNDE1Mi04NDQ4LTAxODk2ZjZiYjFlNyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzc3ODg4ODYwLCJpc3MiOiJQQkwzQVBJIiwiYXVkIjoiUEJMM0NsaWVudCJ9.BMYadVNdD9qREeZC222IgsuJJ6Czz3wP4MgHhrjTe5s
