// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413165940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AddressID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.Property<Guid>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentMethods")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BillID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("StoreID");

                    b.HasIndex("UserID");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Backend.Models.BillChange", b =>
                {
                    b.Property<Guid>("BillChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BillChangeID");

                    b.HasIndex("BillID");

                    b.ToTable("BillChange");
                });

            modelBuilder.Entity("Backend.Models.BillDetail", b =>
                {
                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProductVarientID")
                        .HasColumnType("int");

                    b.Property<decimal>("InlineTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BillID", "ProductVarientID");

                    b.HasIndex("ProductVarientID");

                    b.ToTable("BillDetail");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Backend.Models.Combo", b =>
                {
                    b.Property<int>("ComboID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComboID"));

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ComboID");

                    b.ToTable("Combo");
                });

            modelBuilder.Entity("Backend.Models.ComboProduct", b =>
                {
                    b.Property<int>("ComboID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVarientID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ComboID", "ProductVarientID");

                    b.HasIndex("ProductVarientID");

                    b.ToTable("ComboProduct");
                });

            modelBuilder.Entity("Backend.Models.DeliveryInfo", b =>
                {
                    b.Property<Guid>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("EstimatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("AddressID");

                    b.HasIndex("BillID");

                    b.ToTable("DeliveryInfo");
                });

            modelBuilder.Entity("Backend.Models.DeliveryLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeliveryID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("LogID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("DeliveryLog");
                });

            modelBuilder.Entity("Backend.Models.DiningTable", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableID");

                    b.HasIndex("StoreID");

                    b.ToTable("DiningTable");
                });

            modelBuilder.Entity("Backend.Models.GoodsInspection", b =>
                {
                    b.Property<Guid>("InspectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InspectedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("InspectionID");

                    b.HasIndex("InspectedBy");

                    b.HasIndex("ReceiptID")
                        .IsUnique();

                    b.ToTable("GoodsInspection");
                });

            modelBuilder.Entity("Backend.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientID"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IngredientUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IngredientID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Backend.Models.InspectionDetail", b =>
                {
                    b.Property<Guid>("InspectionID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<string>("DamageReason")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("DamagedQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ExpiredQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GoodQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ShortageQty")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("InspectionID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("InspectionDetail");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.Property<Guid>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchCode")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Exp")
                        .HasColumnType("date");

                    b.Property<Guid>("GoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Mfd")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantityOriginal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ReceiptDetailGoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReceiptDetailIngredientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("BatchID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("ReceiptDetailGoodsReceiptID", "ReceiptDetailIngredientID");

                    b.ToTable("InventoryBatch");
                });

            modelBuilder.Entity("Backend.Models.POApproval", b =>
                {
                    b.Property<Guid>("POID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.HasKey("POID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("POApproval");
                });

            modelBuilder.Entity("Backend.Models.POApprovalChange", b =>
                {
                    b.Property<Guid>("POApprovalChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AftStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BfrStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("POApprovalChangeID");

                    b.ToTable("POApprovalChange");
                });

            modelBuilder.Entity("Backend.Models.PODetail", b =>
                {
                    b.Property<Guid>("POID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("UnitPriceExpected")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("POID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("PODetail");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ProductionTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Backend.Models.ProductVarient", b =>
                {
                    b.Property<int>("ProductVarientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductVarientID"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ProductVarientID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductVarient");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("POID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("StoreID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.Receipe", b =>
                {
                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVarientID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyAfterProcess")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QtyBeforeProcess")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IngredientID", "ProductVarientID");

                    b.HasIndex("ProductVarientID");

                    b.ToTable("Receipe");
                });

            modelBuilder.Entity("Backend.Models.Receipt", b =>
                {
                    b.Property<Guid>("GoodsReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateReceive")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("POID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PurchaseOrderPOID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.HasKey("GoodsReceiptID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("POID")
                        .IsUnique();

                    b.HasIndex("PurchaseOrderPOID");

                    b.HasIndex("StoreID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("Backend.Models.ReceiptDetail", b =>
                {
                    b.Property<Guid>("GoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("GoodsReceiptID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("ReceiptDetail");
                });

            modelBuilder.Entity("Backend.Models.Reservation", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserID", "TableID");

                    b.HasIndex("TableID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChechIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShiftID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Backend.Models.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BatchID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<int?>("IngredientID")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("QtyChange")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StockMovementID");

                    b.HasIndex("BatchID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("IngredientID");

                    b.ToTable("StockMovement");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.HasKey("StoreID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Backend.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupplierID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Backend.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("TicketID");

                    b.HasIndex("UserID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.UserAddress", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserID", "AddressID");

                    b.HasIndex("AddressID");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("WarehouseID");

                    b.HasIndex("StoreID");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasBaseType("Backend.Models.User");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasIndex("StoreID");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.HasOne("Backend.Models.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.BillChange", b =>
                {
                    b.HasOne("Backend.Models.Bill", "Bill")
                        .WithMany("BillChanges")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Backend.Models.BillDetail", b =>
                {
                    b.HasOne("Backend.Models.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProductVarient", "ProductVarient")
                        .WithMany("BillDetails")
                        .HasForeignKey("ProductVarientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("ProductVarient");
                });

            modelBuilder.Entity("Backend.Models.ComboProduct", b =>
                {
                    b.HasOne("Backend.Models.Combo", "Combo")
                        .WithMany("ComboProduct")
                        .HasForeignKey("ComboID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProductVarient", "ProductVarient")
                        .WithMany("ComboProduct")
                        .HasForeignKey("ProductVarientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("ProductVarient");
                });

            modelBuilder.Entity("Backend.Models.DeliveryInfo", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithMany("DeliveryInfos")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Backend.Models.DeliveryLog", b =>
                {
                    b.HasOne("Backend.Models.DeliveryInfo", "DeliveryInfo")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryInfo");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Backend.Models.DiningTable", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("DiningTables")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Backend.Models.GoodsInspection", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("GoodsInspections")
                        .HasForeignKey("InspectedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Receipt", "Receipt")
                        .WithOne("GoodsInspection")
                        .HasForeignKey("Backend.Models.GoodsInspection", "ReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Backend.Models.InspectionDetail", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("InspectionDetails")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.GoodsInspection", "GoodsInspection")
                        .WithMany("InspectionDetails")
                        .HasForeignKey("InspectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsInspection");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ReceiptDetail", "ReceiptDetail")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("ReceiptDetailGoodsReceiptID", "ReceiptDetailIngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ReceiptDetail");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.POApproval", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("POApprovals")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("POApprovals")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.PODetail", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("PODetails")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PODetails")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.ProductVarient", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("ProductVarients")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Backend.Models.Receipe", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProductVarient", "ProductVarient")
                        .WithMany("Recipes")
                        .HasForeignKey("ProductVarientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ProductVarient");
                });

            modelBuilder.Entity("Backend.Models.Receipt", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Deleted")
                        .WithMany("DeletedReceipts")
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("Receipts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", "PurchaseOrder")
                        .WithOne("Receipt")
                        .HasForeignKey("Backend.Models.Receipt", "POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", null)
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PurchaseOrderPOID");

                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deleted");

                    b.Navigation("Employee");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Backend.Models.ReceiptDetail", b =>
                {
                    b.HasOne("Backend.Models.Receipt", "Receipt")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("GoodsReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Backend.Models.Reservation", b =>
                {
                    b.HasOne("Backend.Models.DiningTable", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Backend.Models.StockMovement", b =>
                {
                    b.HasOne("Backend.Models.InventoryBatch", "Batch")
                        .WithMany("StockMovements")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("StockMovements")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", null)
                        .WithMany("StockMovements")
                        .HasForeignKey("IngredientID");

                    b.Navigation("Batch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithOne("Store")
                        .HasForeignKey("Backend.Models.Store", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Backend.Models.Supplier", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithOne("Supplier")
                        .HasForeignKey("Backend.Models.Supplier", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Backend.Models.Ticket", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Ticket")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserAddress", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("Warehouses")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Navigation("DeliveryInfos");

                    b.Navigation("Store");

                    b.Navigation("Supplier");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.Navigation("BillChanges");

                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Combo", b =>
                {
                    b.Navigation("ComboProduct");
                });

            modelBuilder.Entity("Backend.Models.DeliveryInfo", b =>
                {
                    b.Navigation("DeliveryLogs");
                });

            modelBuilder.Entity("Backend.Models.DiningTable", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Backend.Models.GoodsInspection", b =>
                {
                    b.Navigation("InspectionDetails");
                });

            modelBuilder.Entity("Backend.Models.Ingredient", b =>
                {
                    b.Navigation("InspectionDetails");

                    b.Navigation("InventoryBatches");

                    b.Navigation("PODetails");

                    b.Navigation("ReceiptDetails");

                    b.Navigation("Recipes");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("ProductVarients");
                });

            modelBuilder.Entity("Backend.Models.ProductVarient", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("ComboProduct");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("POApprovals");

                    b.Navigation("PODetails");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Backend.Models.Receipt", b =>
                {
                    b.Navigation("GoodsInspection");

                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("Backend.Models.ReceiptDetail", b =>
                {
                    b.Navigation("InventoryBatches");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.Navigation("DiningTables");

                    b.Navigation("Employees");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Ticket");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Navigation("InventoryBatches");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("DeletedReceipts");

                    b.Navigation("DeliveryLogs");

                    b.Navigation("GoodsInspections");

                    b.Navigation("POApprovals");

                    b.Navigation("Receipts");

                    b.Navigation("Shifts");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
