// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AddressID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.Property<Guid>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentMethods")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BillID");

                    b.HasIndex("StoreID");

                    b.HasIndex("UserID");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Backend.Models.BillDetail", b =>
                {
                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("InlineTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BillID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("BillDetail");
                });

            modelBuilder.Entity("Backend.Models.BillModify", b =>
                {
                    b.Property<Guid>("BillModifyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillDetailBillID")
                        .HasColumnType("char(36)");

                    b.Property<int>("BillDetailProductID")
                        .HasColumnType("int");

                    b.Property<Guid>("BillID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ModifyType")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("BillModifyID");

                    b.HasIndex("BillDetailBillID", "BillDetailProductID");

                    b.ToTable("BillModify");
                });

            modelBuilder.Entity("Backend.Models.GoodsReceipt", b =>
                {
                    b.Property<Guid>("GoodsReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateReceive")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.HasKey("GoodsReceiptID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("StoreID");

                    b.HasIndex("SupplierID");

                    b.ToTable("GoodsReceipt");
                });

            modelBuilder.Entity("Backend.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientID"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IngredientUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IngredientID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.Property<Guid>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchCode")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Exp")
                        .HasColumnType("date");

                    b.Property<Guid>("GoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Mfd")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantityOriginal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ReceiptDetailGoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReceiptDetailIngredientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("BatchID");

                    b.HasIndex("GoodsReceiptID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("WarehouseID");

                    b.HasIndex("ReceiptDetailGoodsReceiptID", "ReceiptDetailIngredientID");

                    b.ToTable("InventoryBatch");
                });

            modelBuilder.Entity("Backend.Models.POApproval", b =>
                {
                    b.Property<Guid>("POID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("POID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("POApproval");
                });

            modelBuilder.Entity("Backend.Models.PODetail", b =>
                {
                    b.Property<Guid>("POID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("UnitPriceExpected")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("POID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("PODetail");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ProductionTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("POID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("StoreID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.Receipe", b =>
                {
                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyAfterProcess")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QtyBeforeProcess")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IngredientID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("Receipe");
                });

            modelBuilder.Entity("Backend.Models.ReceiptDetail", b =>
                {
                    b.Property<Guid>("GoodsReceiptID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("GoodsReceiptID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("ReceiptDetail");
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChechIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShiftID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Backend.Models.StockAudit", b =>
                {
                    b.Property<Guid>("StockAuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("StockAuditID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreateBy");

                    b.HasIndex("WarehouseID");

                    b.ToTable("StockAudit");
                });

            modelBuilder.Entity("Backend.Models.StockAuditDetail", b =>
                {
                    b.Property<Guid>("StockAuditID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BatchID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CounterQty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Difference")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("IngredientID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SysQty")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("StockAuditID", "BatchID");

                    b.HasIndex("BatchID");

                    b.HasIndex("IngredientID");

                    b.ToTable("StockAuditDetail");
                });

            modelBuilder.Entity("Backend.Models.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BatchID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("char(36)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("QtyChange")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceID")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("StockMovementID");

                    b.HasIndex("BatchID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("StockMovement");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.HasKey("StoreID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Backend.Models.StoreUtility", b =>
                {
                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<int>("UtilityID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("StoreID", "UtilityID");

                    b.HasIndex("UtilityID");

                    b.ToTable("StoreUtility");
                });

            modelBuilder.Entity("Backend.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupplierID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Backend.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("TicketID");

                    b.HasIndex("UserID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.UserAddress", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserID", "AddressID");

                    b.HasIndex("AddressID");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("Backend.Models.Utility", b =>
                {
                    b.Property<int>("UtilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UtilityID"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UtilityID");

                    b.ToTable("Utility");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("WarehouseID");

                    b.HasIndex("StoreID");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasBaseType("Backend.Models.User");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasIndex("StoreID");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.BillDetail", b =>
                {
                    b.HasOne("Backend.Models.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("BillDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.BillModify", b =>
                {
                    b.HasOne("Backend.Models.BillDetail", "BillDetail")
                        .WithMany()
                        .HasForeignKey("BillDetailBillID", "BillDetailProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillDetail");
                });

            modelBuilder.Entity("Backend.Models.GoodsReceipt", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.HasOne("Backend.Models.GoodsReceipt", null)
                        .WithMany("InventoryBatches")
                        .HasForeignKey("GoodsReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ReceiptDetail", "ReceiptDetail")
                        .WithMany()
                        .HasForeignKey("ReceiptDetailGoodsReceiptID", "ReceiptDetailIngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ReceiptDetail");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.POApproval", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("POApprovals")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("POApprovals")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.PODetail", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("PODetails")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PODetails")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Backend.Models.Receipe", b =>
                {
                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Recipes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.ReceiptDetail", b =>
                {
                    b.HasOne("Backend.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("GoodsReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Backend.Models.StockAudit", b =>
                {
                    b.HasOne("Backend.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("Backend.Models.Employee", "CreateByEmployee")
                        .WithMany()
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("CreateByEmployee");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.StockAuditDetail", b =>
                {
                    b.HasOne("Backend.Models.InventoryBatch", "InventoryBatch")
                        .WithMany("StockAuditDetails")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", null)
                        .WithMany("StockAuditDetails")
                        .HasForeignKey("IngredientID");

                    b.HasOne("Backend.Models.StockAudit", "StockAudit")
                        .WithMany("StockAuditDetails")
                        .HasForeignKey("StockAuditID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryBatch");

                    b.Navigation("StockAudit");
                });

            modelBuilder.Entity("Backend.Models.StockMovement", b =>
                {
                    b.HasOne("Backend.Models.InventoryBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchID");

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Employee");

                    b.Navigation("Ingredient");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithOne("Store")
                        .HasForeignKey("Backend.Models.Store", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Backend.Models.StoreUtility", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("StoreUtilities")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utility", "Utility")
                        .WithMany("StoreUtility")
                        .HasForeignKey("UtilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("Backend.Models.Supplier", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithOne("Supplier")
                        .HasForeignKey("Backend.Models.Supplier", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Backend.Models.Ticket", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Ticket")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserAddress", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("Warehouses")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Navigation("Store");

                    b.Navigation("Supplier");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("Backend.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Backend.Models.GoodsReceipt", b =>
                {
                    b.Navigation("InventoryBatches");

                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("Backend.Models.Ingredient", b =>
                {
                    b.Navigation("InventoryBatches");

                    b.Navigation("PODetails");

                    b.Navigation("ReceiptDetails");

                    b.Navigation("Recipes");

                    b.Navigation("StockAuditDetails");
                });

            modelBuilder.Entity("Backend.Models.InventoryBatch", b =>
                {
                    b.Navigation("StockAuditDetails");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Backend.Models.PurchaseOrder", b =>
                {
                    b.Navigation("POApprovals");

                    b.Navigation("PODetails");
                });

            modelBuilder.Entity("Backend.Models.StockAudit", b =>
                {
                    b.Navigation("StockAuditDetails");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("StoreUtilities");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Ticket");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Backend.Models.Utility", b =>
                {
                    b.Navigation("StoreUtility");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Navigation("InventoryBatches");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("POApprovals");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
